# Generated by Django 5.2.5 on 2025-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('payme', 'Payme'), ('click', 'Click'), ('atmos', 'Atmos'), ('uzum', 'Uzum')], max_length=10, null=True),
        ),
    ]
